spring:
  application:
    name: tinkoff-bot-api

  liquibase:
    change-log: classpath:db/changelog/db.changelog.master.xml
    user: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jackson:
    serialization:
      fail-on-empty-beans: false
app:
  sandbox:
    token: ${TINKOFF_TOKEN}
  account:
    id: ${TINKOFF_ACCOUNT_ID}

server:
  port: 9999
