version: "3.2"
services:
  postgres:
    image: postgres:16
    restart: always
    env_file:
      - /postgres/.env
    ports:
      - "5432:5432"
    volumes:
      - /containers/postgres/:/var/lib/postgresql/data/
      - /containers/postgres/scripts:/docker-entrypoint-initdb.d
